"""Data models for Google Health API."""

from .activity import (
    ACTIVE_ENERGY_BURNED,
    BASAL_ENERGY_BURNED,
    DISTANCE,
    FLOORS,
    STEPS,
    TOTAL_CALORIES,
    ActiveEnergyBurned,
    ActiveEnergyBurnedRollupValue,
    BasalEnergyBurned,
    Distance,
    DistanceRollupValue,
    Floors,
    FloorsRollupValue,
    Steps,
    StepsRollupValue,
    TotalCaloriesRollupValue,
)
from .base import (
    DailyRollupDataPoint,
    DataPoint,
    DataSource,
    DataType,
    ReconciledDataPoint,
)
from .device import ListPairedDevicesResult, PairedDevice, _ListPairedDevicesModel
from .health_metric import (
    DAILY_RESTING_HEART_RATE,
    HEART_RATE,
    VO2_MAX,
    WEIGHT,
    DailyRestingHeartRate,
    DailyRestingHeartRateMetadata,
    HeartRate,
    VO2Max,
    Weight,
)
from .hydration import (
    HYDRATION_LOG,
    HydrationLog,
    HydrationLogRollupValue,
    VolumeQuantity,
    VolumeQuantityRollup,
)
from .nutrition import (
    NUTRITION_LOG,
    NutritionLog,
    NutritionLogRollupValue,
    WeightQuantity,
    EnergyQuantity,
    Serving,
    NutrientQuantity,
    WeightQuantityRollup,
    EnergyQuantityRollup,
    NutrientQuantityRollup,
)
from .pagination import (
    ListDataPointResult,
    ListReconciledDataPointsResult,
    _ListDataPointsModel,
    _ListReconciledDataPointsModel,
)
from .operation import Operation, Status
from .profile import Date, Identity, IrnProfile, Profile
from .settings import Settings
from .sleep import (
    SLEEP,
    CivilDateTime,
    CivilTimeInterval,
    DailyRollUpDataPointsRequest,
    OutOfBedSegment,
    SessionTimeInterval,
    Sleep,
    SleepMetadata,
    SleepStage,
    SleepSummary,
    StageSummary,
    TimeOfDay,
)
from .subscription import (
    EndpointAuthorization,
    ListSubscribersResult,
    ListSubscriptionsResult,
    Subscriber,
    SubscriberConfig,
    Subscription,
    _ListSubscribersModel,
    _ListSubscriptionsModel,
)

__all__ = [
    # --- Core & Base API Structures ---
    "DataType",
    "DataPoint",
    "ReconciledDataPoint",
    "DataSource",
    "DailyRollupDataPoint",
    # --- Activity Models ---
    "Steps",
    "STEPS",
    "Distance",
    "DISTANCE",
    "BasalEnergyBurned",
    "BASAL_ENERGY_BURNED",
    "ActiveEnergyBurned",
    "ACTIVE_ENERGY_BURNED",
    "TOTAL_CALORIES",
    "StepsRollupValue",
    "DistanceRollupValue",
    "ActiveEnergyBurnedRollupValue",
    "TotalCaloriesRollupValue",
    "Floors",
    "FLOORS",
    "FloorsRollupValue",
    # --- Health Metric Models ---
    "HeartRate",
    "HEART_RATE",
    "VO2Max",
    "VO2_MAX",
    "Weight",
    "WEIGHT",
    "DailyRestingHeartRate",
    "DAILY_RESTING_HEART_RATE",
    "DailyRestingHeartRateMetadata",
    # --- Sleep Models ---
    "Sleep",
    "SLEEP",
    # --- Hydration Models ---
    "HydrationLog",
    "HYDRATION_LOG",
    "HydrationLogRollupValue",
    "VolumeQuantity",
    "VolumeQuantityRollup",
    # --- Nutrition Models ---
    "NutritionLog",
    "NUTRITION_LOG",
    "NutritionLogRollupValue",
    "WeightQuantity",
    "EnergyQuantity",
    "Serving",
    "NutrientQuantity",
    "WeightQuantityRollup",
    "EnergyQuantityRollup",
    "NutrientQuantityRollup",
    "SessionTimeInterval",
    "CivilDateTime",
    "CivilTimeInterval",
    "DailyRollUpDataPointsRequest",
    "TimeOfDay",
    "SleepStage",
    "OutOfBedSegment",
    "SleepSummary",
    "StageSummary",
    "SleepMetadata",
    # --- Profile & Settings Models ---
    "Profile",
    "IrnProfile",
    "Identity",
    "Settings",
    "Date",
    # --- Device & Webhook Subscription Models ---
    "PairedDevice",
    "Subscriber",
    "SubscriberConfig",
    "EndpointAuthorization",
    "Subscription",
    "Operation",
    "Status",
    # --- Pagination & Internal Result wrappers ---
    "ListDataPointResult",
    "ListReconciledDataPointsResult",
    "ListPairedDevicesResult",
    "ListSubscribersResult",
    "ListSubscriptionsResult",
    "_ListDataPointsModel",
    "_ListReconciledDataPointsModel",
    "_ListPairedDevicesModel",
    "_ListSubscribersModel",
    "_ListSubscriptionsModel",
]
